version: '3'
services:
    remotemark:
        image:
            remotemark
        container_name:
            remotemark_alpha
        build:
            context:
                .
#           args:
#               http_proxy: http://user_abc:password@proxy.example.com:8080/
#               https_proxy: http://user_abc:password@proxy.example.com:8080/
        ports:
            - 8080:80
        privileged:
            true
#       environment:
#           http_proxy: http://user_abc:password@proxy.example.com:8080/
#           https_proxy: http://user_abc:password@proxy.example.com:8080/
        volumes:
            - pv:/var/www/cgi-bin/data
        command:
            bash -c 'bash startup.sh && /sbin/init'

# mkdir pv しておくこと
volumes:
    pv:
        driver_opts:
            type: none
            device: /root/docker/remotemark/pv
            o: bind

